apiVersion: v1
kind: Service
metadata:
  name: playzone-service
  namespace: playzone
spec:
  selector:
    app: playzone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
